scene:
  /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/Export_Matis_EXPORT_1246-13704.3DS

labels:
  labels_dir:
    /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/_labels
  depth: 1
  LoD: 2
  hierarchical: True

features:
  geometric:
    graph_dir:
      /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/dual_graphs
    statistics:
      histogram
    attributes:
      - degree
      - angle
  altimetric:
    raster_dir:
      /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/rasters
    resolution: 100

processing:
  visualization:
    manifold:
      algorithm: DictionaryLearning
      parameters:
        n_components: 100
    dimension_reduction:
      algorithm: PCA
      parameters:
        n_components: 3
  classification:
    data_separation:
      cross_validation:
        10
    algorithm:
      name: RandomForestClassifier
      trees: 1000
      depth: 4
