scene:
    /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/Export_Matis_EXPORT_1246-13704.3DS

labels:
    labels_path:
        /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/ground_truth.csv
    depth: 3
    LoD: 2
    hierarchical: False
    filetype: csv
    threshold: 5

features:
    geometric:
        graph_dir:
            /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/dual_graphs
        statistics:
            - mean
            - median
            - max
            - min
        attributes:
            - degree
            - angle_with_relations
            - centroid_with_relations
            - area
    altimetric:
        raster_dir:
            /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/rasters
        dsm_dir: '/home/ethiy/Data/Elancourt/DSM'
        ext: tiff
        dsm_ext: geotiff
        high_res: 5
        low_res: 5
    radiometric:
        vector_dir: /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/_labels
        ortho_dir: /home/ethiy/Data/Elancourt/OrthoImages
        ext: 'geotiff'
        vector_ext: 'shp'
        clip: True
        bins: 5

processing:
    visualization:
        manifold:
            algorithm: sklearn.decomposition.KernelPCA
            parameters:
                n_components: 10
        dimension_reduction:
            algorithm: sklearn.decomposition.PCA
            parameters:
                n_components: 3
        style:
            colors:
                - g
                - r
                - b
            markers:
                - ','
                - o
                - ^
    classification:
        data_separation:
            cross_validation:
                parameters:
                    n_splits: 4
        training:
            model:
                algorithm:
                    sklearn.ensemble.RandomForestClassifier
                parameters:
                    max_depth: 4
                    n_estimators: 800
                strategy:
                    sklearn.multiclass.OneVsRestClassifier
                save:
                    onevrest_rf-d4-n800_nonhier-depth3-lod1
        testing:
            predictions:
                filename: predictions
