scene:
    /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/Export_Matis_EXPORT_1246-13704.3DS

labels:
    labels_dir:
        /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/_labels
    depth: 3
    LoD: 2
    hierarchical: False

features:
    geometric:
        graph_dir:
            /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/dual_graphs
        statistics:
            - mean
            - median
            - max
            - min
        attributes:
            - degree
            - angle_with_relations
            - centroid_with_relations
            - area
    altimetric:
        raster_dir:
            /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/rasters
        resolution: 5

processing:
    visualization:
        manifold:
            algorithm: sklearn.decomposition.KernelPCA
            parameters:
                n_components: 10
        dimension_reduction:
            algorithm: sklearn.decomposition.PCA
            parameters:
                n_components: 3
        style:
            colors:
                - g
                - r
                - b
            markers:
                - ','
                - o
                - ^
    classification:
        data_separation:
            train_test_split:
                parameters:
                    test_size: 1
        training:
            model:
                filename: model.pkl
                save: model
        testing:
            score:
                - sklearn.metrics.accuracy_score
        predictions:
            probabilities: False
            filename: results
