cache:
    /home/ethiy/Data/Assembled/__

labels:
    labels_path:
        /home/ethiy/Data/Assembled/ground_truth_paris_13.csv
    depth: 3
    LoD: 2
    hierarchical: False
    filetype: csv
    threshold: 10

features:
    types:
        geometric:
            graph_dir:
               /home/ethiy/Data/Assembled/facet_graphs
            method: 
                graph
            parameters:
                list:
                    graph_1:
                        node_attributes: 
                            - normal
                    graph_2:
                        node_attributes: 
                            - area
        # altimetric:
        #     model_dir:
        #         /home/ethiy/Data/Assembled/raster_projections
        #     dsm_dir: '/home/ethiy/Data/Assembled/DSM'
        #     model_ext: tiff
        #     dsm_ext: geotiff
        #     method: histogram
        #     margins: !!python/tuple [0,0]
        #     parameters:
        #         resolution: 20
        #         max_amplitude: 50
        # radiometric:
        #     vector_dir: /home/ethiy/Data/Assembled/vector_projections
        #     ortho_dir: '/home/ethiy/Data/Assembled/Orthoimages'
        #     ortho_ext: 'geotiff'
        #     vector_ext: 'shp'
        #     method: gradient
        #     parameters:
        #         resolution: 20
        #         weight: (True, True, True)
    format:
        kernel:
            geometric:
                graph_1:
                    algorithm:
                        classe:
                            grakel.GraphKernel
                        parameters:
                            kernel: 
                                name: lovasz_theta
                            n_jobs: 8
                            normalize: True
                graph_2:
                    algorithm:
                        classe:
                            grakel.GraphKernel
                        parameters:
                            kernel: 
                                name: lovasz_theta
                            normalize: True
                            n_jobs: 8

            # altimetric:
            #     algorithm:
            #         sklearn.metrics.pairwise.rbf_kernel
            #     parameters:
            #         gamma: 0.05
            # radiometric:
            #     algorithm:
            #         sklearn.metrics.pairwise.rbf_kernel
            #     parameters:
            #         gamma: 0.001
processing:
    # visualization:
    #     dimension_reduction:
    #         algorithm: sklearn.decomposition.PCA
    #         parameters:
    #             n_components: 3
    #     style:
    #         colors:
    #             - g
    #             - r
    #             - b
    #         markers:
    #             - ','
    #             - o
    #             - ^
    classification:
        data_separation:
            cross_validation:
                parameters:
                    n_splits: 10
        training:
            model:
                algorithm:
                    sklearn.svm.SVC
                parameters:
                    kernel: precomputed
                    C: 0.1
                    probability: True
                    class_weight: balanced
                strategy:
                    sklearn.multiclass.OneVsRestClassifier
        testing:
            predictions:
                filename: predictions-2
