cache:
    /home/ubuntu/Assembled/cache

labels:
    labels_path:
        /home/ubuntu/Assembled/ground_truth_elancourt_paris_13+nantes.csv
    depth: 1
    LoD: 2
    hierarchical: True
    filetype: csv
    threshold: 10

features:
    types:
        geometric:
            graph_dir:
               /home/ubuntu/Assembled/facet_graphs
            statistics:
                - mean
                - median
                - max
                - min
            attributes:
                - degree
                - angle_with_relations
                - centroid_with_relations
                - area
                - circumference
        # altimetric:
        #     model_dir:
        #         /home/ubuntu/Assembled/raster_projections
        #     dsm_dir: '/home/ubuntu/Assembled/DSM'
        #     model_ext: tiff
        #     dsm_ext: geotiff
        #     method: histogram
        #     margins: (0, 0)
        #     parameters:
        #         resolution: 20
        # radiometric:
        #     vector_dir: /home/ubuntu/Assembled/vector_projections
        #     ortho_dir: '/home/ubuntu/Assembled/Orthoimages'
        #     ortho_ext: 'geotiff'
        #     vector_ext: 'shp'
        #     method: gradient
        #     parameters:
        #         resolution: 10
        #         weight: (True, True, True)
    # manifold:
    #     algorithm: sklearn.decomposition.KernelPCA
    #     parameters:
    #         kernel: 'rbf'
    #         gamma: .0000001
    #         n_components: 3
processing:
    # visualization:
    #     dimension_reduction:
    #         algorithm: sklearn.decomposition.PCA
    #         parameters:
    #             n_components: 3
    #     style:
    #         colors:
    #             - g
    #             - r
    #             - b
    #         markers:
    #             - ','
    #             - o
    #             - ^
    classification:
        data_separation:
            train_test_split:
                parameters:
                    train_size: .3
        training:
            model:
                algorithm:
                    sklearn.ensemble.RandomForestClassifier
                parameters:
                    max_depth: 4
                    n_estimators: 1000
                strategy:
                    sklearn.multiclass.OneVsRestClassifier
        testing:
            predictions:
                filename: predictions-2
