cache:
    /home/ethiy/Data/Assembled/__

labels:
    labels_path:
        /home/ethiy/Data/Assembled/ground_truth_paris_13.csv
    depth: 3
    LoD: 2
    hierarchical: False
    filetype: csv
    threshold: 10

features:
    types:
        # geometric:
        #     graph_dir:
        #        /home/ethiy/Data/Assembled/facet_graphs
        #     method: 
        #         graph
        #     parameters:
        #             # graph_1:
        #             #     edge_attributes: 
        #             #         - normal
        #             # graph_2:
        #             #     edge_attributes: 
        #             #         - centroid
        #             graph_3:
        #                 node_attributes: 
        #                     - area
        #             # graph_4:
        #             #     node_attributes: 
        #             #         - circumference
        altimetric:
            model_dir:
                /home/ethiy/Data/Assembled/raster_projections
            dsm_dir: '/home/ethiy/Data/Assembled/DSM'
            model_ext: tiff
            dsm_ext: geotiff
            margins: !!python/tuple [0,0]
            methods:
                - method: rmse
                - method: histogram
                  parameters:
                      resolution: 20
                      max_amplitude: 50
        radiometric:
            vector_dir: /home/ethiy/Data/Assembled/vector_projections
            ortho_dir: '/home/ethiy/Data/Assembled/Orthoimages'
            ortho_ext: 'geotiff'
            vector_ext: 'shp'
            methods:
                - method: gradient
                  parameters:
                      resolution: 20
                      weight: (True, True, True)
    format:
        kernel:
            # geometric:
                # graph_1:
                #     algorithm:
                #         classe:
                #             grakel.GraphKernel
                #         parameters:
                #             kernel: 
                #                 name: random_walk
                #                 lamda: .017
                #                 kernel_type: geometric
                #                 method_type: fast
                #             n_jobs: 8
                #             normalize: True
                # graph_2:
                #     algorithm:
                #         classe:
                #             grakel.GraphKernel
                #         parameters:
                #             kernel:
                #                 - name: core_framework
                #                 - name: random_walk
                #                   lamda: .02
                #                   kernel_type: geometric
                #                   method_type: fast
                #                   n_jobs: 8
                #             normalize: True
                # graph_3:
                #     algorithm:
                #         classe:
                #             grakel.GraphKernel
                #         parameters:
                #             kernel: 
                #                 name: svm_theta
                #             normalize: True
                #             n_jobs: 1
                # graph_4:
                #     algorithm:
                #         classe:
                #             grakel.GraphKernel
                #         parameters:
                #             kernel: 
                #                 name: svm_theta
                #             normalize: True
                #             n_jobs: 1

            altimetric:
                rmse:
                    type: callable
                    algorithm:
                        sklearn.metrics.pairwise.rbf_kernel
                    parameters:
                        gamma: 0.05
                histogram:
                    type: callable
                    algorithm:
                        sklearn.metrics.pairwise.rbf_kernel
                    parameters:
                        gamma: 0.05
            altimetric:
                gradient:
                    type: callable
                    algorithm:
                        sklearn.metrics.pairwise.rbf_kernel
                    parameters:
                        gamma: 0.05
processing:
    # visualization:
    #     dimension_reduction:
    #         algorithm: sklearn.decomposition.PCA
    #         parameters:
    #             n_components: 3
    #     style:
    #         colors:
    #             - g
    #             - r
    #             - b
    #         markers:
    #             - ','
    #             - o
    #             - ^
    classification:
        data_separation:
            bipartite:
                threshold: 454
        training:
            model:
                algorithm:
                    sklearn.svm.SVC
                parameters:
                    kernel: precomputed
                    C: 1
                    probability: True
                    class_weight: balanced
                strategy:
                    sklearn.multiclass.OneVsRestClassifier
        testing:
            predictions:
                filename: predictions-2
