scene:
    /home/ethiy/Data/Elancourt/Bati3D/EXPORT_1246-13704/export-3DS/Export_Matis_EXPORT_1246-13704.3DS

labels:
    labels_path:
        /home/ethiy/Data/Elancourt/ground_truth.csv
    depth: 3
    LoD: 2
    hierarchical: False
    filetype: csv
    threshold: 10

features:
    types:
        # geometric:
        #     graph_dir:
        #         /home/ethiy/Data/Elancourt/projections/dual_graphs
        #     statistics:
        #         - mean
        #         - median
        #         - max
        #         - min
        #     attributes:
        #         - degree
        #         - angle_with_relations
        #         - centroid_with_relations
        #         - area
        altimetric:
            model_dir:
                /home/ethiy/Data/Elancourt/projections/rasters
            dsm_dir: '/home/ethiy/Data/Elancourt/DSM'
            margins: (0, 0)
            model_ext: tiff
            dsm_ext: geotiff
            resolution: 10
        # radiometric:
        #     vector_dir: /home/ethiy/Data/Elancourt/projections/vectors
        #     ortho_dir: /home/ethiy/Data/Elancourt/OrthoImages
        #     ortho_ext: 'geotiff'
        #     vector_ext: 'shp'
        #     method: gradient
        #     parameters:
        #         resolution: 10
        #         weight: (True, True, True)
    # manifold:
    #     algorithm: sklearn.decomposition.KernelPCA
    #     parameters:
    #         kernel: 'rbf'
    #         gamma: .0000001
    #         n_components: 10
processing:
    visualization:
        dimension_reduction:
            algorithm: sklearn.decomposition.PCA
            parameters:
                n_components: 3
        style:
            colors:
                - g
                - r
                - b
            markers:
                - ','
                - o
                - ^
    classification:
        data_separation:
            cross_validation:
                parameters:
                    n_splits: 10
        training:
            model:
                algorithm:
                    sklearn.ensemble.RandomForestClassifier
                parameters:
                    max_depth: 4
                    n_estimators: 1000
                strategy:
                    sklearn.multiclass.OneVsRestClassifier
                save:
                    onevrest_rf-d4-n1000_nonhier-depth3-lod2
        testing:
            predictions:
                filename: predictions
